### ISSUE TITLE
Terminal colors are used when emacs is started from daemon

### ISSUE THREAD

**Issue by sabof** [emacsfodder/emacs-soothe-theme#1]
Not sure if the functionality exists in OS X, but daemon starts as terminal - at which point the theme is most likely to be loaded, and later one can connect X frames to it, so the shortcut you've used doesn't work. However you can specify different colors for different display types in the face specification.

**Comment by jasonm23** [comment]
Terminal color support is only for terms which support `COLORTERM=truecolor`.
