### ISSUE TITLE
Theme looks bad in ediff mode

### ISSUE THREAD

**Issue by edvorg** [emacsfodder/emacs-soothe-theme#16]
Highlighted text is not readable

![screen shot 2015-04-06 at 11 04 43 am](https://cloud.githubusercontent.com/assets/1499595/7002052/e0b2f792-dc4c-11e4-900f-cdd92a481f8c.png)

**Comment by jasonm23** [comment]
Please place the cursor/point on the highlighted text and do:

    M-x describe-face

Let me know the name of the face you are prompted with. Thank you.

**Comment by edvorg** [comment]
`ediff-fine-diff-B` is suggested.

**Comment by edvorg** [comment]
also `ediff-current-diff-B` not contrast enough.

**Comment by jasonm23** [comment]
Ok, thank you

**Comment by jasonm23** [comment]
it was overhauled and includes better diff/smerge/ediff support.
